import { CompanyProfile } from '@/types/customer';
import { MaterialOption, HardwareOption, ProductCategoryPreset } from '@/types/catalog';
import { Customer } from '@/types/customer';

export const DEFAULT_COMPANY_PROFILE: CompanyProfile = {
  name: 'VLR Interior Solutions',
  tagline: 'Premium Modular Kitchens & Customized Interior Craftsmanship',
  address: 'Plot 42, Commercial Complex, Sector 18',
  city: 'Hyderabad, Telangana - 500081',
  phone: '+91 98765 43210',
  email: 'quotations@vlrinteriors.com',
  website: 'www.vlrinteriors.com',
  gstin: '36ABCDE1234F1Z5',
  pan: 'ABCDE1234F',
  bankDetails: {
    bankName: 'HDFC Bank Ltd',
    accountName: 'VLR Interior Solutions Pvt Ltd',
    accountNumber: '50200012345678',
    ifscCode: 'HDFC0001234',
    branchName: 'Sector 18 Branch',
    upiId: 'vlrinteriors@hdfcbank',
  },
  termsAndConditions: [
    'Quotation validity is 30 days from the date of issuance.',
    '50% advance payment required upon order confirmation.',
    '40% payment on arrival of material at site prior to installation.',
    'Balance 10% payment upon completion of installation.',
    'Delivery timeframe is 3 to 4 weeks from technical drawing approval date.',
    'Civil, electrical, and plumbing works are excluded unless explicitly specified.',
  ],
  warrantyNotes: '5-Year Structural Warranty on HDMR/BWP Plywood & Lifetime Warranty on Soft-Close Hinges.',
  footerMessage: 'Thank you for choosing VLR Interior Solutions. We appreciate your business!',
};

export const DEFAULT_MATERIALS: MaterialOption[] = [
  {
    id: 'mat_1',
    name: '1mm High Gloss Laminate (SF)',
    type: 'shutter',
    category: 'Laminate',
    brand: 'Merino / Century',
    thicknessMm: 1,
    finish: 'High Gloss',
    rateModifierSqFt: 0,
  },
  {
    id: 'mat_2',
    name: '18mm BWP Plywood Carcass (IS 710)',
    type: 'carcass',
    category: 'Plywood',
    brand: 'Greenply / Century',
    thicknessMm: 18,
    finish: 'Calibrated BWP',
    rateModifierSqFt: 50,
  },
  {
    id: 'mat_3',
    name: '18mm HDMR Water Resistant Board',
    type: 'carcass',
    category: 'HDMR',
    brand: 'Action TESA',
    thicknessMm: 18,
    finish: 'Standard HDMR',
    rateModifierSqFt: 0,
  },
  {
    id: 'mat_4',
    name: '2mm Anti-Scratch Acrylic Finish',
    type: 'shutter',
    category: 'Acrylic',
    brand: 'Rehau / Senosan',
    thicknessMm: 2,
    finish: 'Ultra High Gloss',
    rateModifierSqFt: 250,
  },
  {
    id: 'mat_5',
    name: 'PU Paint Matt / High Gloss',
    type: 'shutter',
    category: 'PU Paint',
    brand: 'ICA / Asian Paints',
    finish: 'Satin PU',
    rateModifierSqFt: 450,
  },
  {
    id: 'mat_6',
    name: 'Natural Teak Wood Veneer with PU Polish',
    type: 'shutter',
    category: 'Veneer',
    brand: 'Decowood',
    thicknessMm: 4,
    finish: 'Natural Wood',
    rateModifierSqFt: 550,
  },
];

export const DEFAULT_HARDWARE: HardwareOption[] = [
  {
    id: 'hw_1',
    name: 'Hettich Sensys Soft-Close Package',
    brand: 'Hettich',
    description: 'German 3D clip-on soft-close hinges & tandem box drawers',
    packagePricePerUnit: 1800,
  },
  {
    id: 'hw_2',
    name: 'Hafele Metalla Soft-Close Hinges',
    brand: 'Hafele',
    description: 'Hafele Matrix Box soft-close runner system',
    packagePricePerUnit: 1500,
  },
  {
    id: 'hw_3',
    name: 'Ebco Soft-Close Drawer Rails',
    brand: 'Ebco',
    description: 'Ebco heavy duty telescopic soft-close channels',
    packagePricePerUnit: 800,
  },
  {
    id: 'hw_4',
    name: 'Godrej Ultra Lock & Hinge Set',
    brand: 'Godrej',
    description: 'Godrej wardrobe safety locks & heavy duty hinges',
    packagePricePerUnit: 1200,
  },
];

export const DEFAULT_PRODUCT_PRESETS: ProductCategoryPreset[] = [
  {
    id: 'preset_wardrobe',
    category: 'Wardrobe',
    defaultName: 'Master Bedroom Hinged Wardrobe',
    defaultPricingModel: 'sqft',
    defaultRate: 1450,
    defaultDepthInches: 24,
    carcassMaterialId: 'mat_3',
    shutterMaterialId: 'mat_1',
    hardwareOptionId: 'hw_1',
  },
  {
    id: 'preset_sliding_wardrobe',
    category: 'Wardrobe',
    defaultName: 'Sliding Door Wardrobe with Loft',
    defaultPricingModel: 'sqft',
    defaultRate: 1750,
    defaultDepthInches: 26,
    carcassMaterialId: 'mat_2',
    shutterMaterialId: 'mat_4',
    hardwareOptionId: 'hw_2',
  },
  {
    id: 'preset_kitchen',
    category: 'Kitchen',
    defaultName: 'Modular Kitchen Base & Wall Units',
    defaultPricingModel: 'sqft',
    defaultRate: 1650,
    defaultDepthInches: 24,
    carcassMaterialId: 'mat_2',
    shutterMaterialId: 'mat_4',
    hardwareOptionId: 'hw_1',
  },
  {
    id: 'preset_tv_unit',
    category: 'TV Unit',
    defaultName: 'Living Room Floating TV Unit with Paneling',
    defaultPricingModel: 'sqft',
    defaultRate: 1350,
    defaultDepthInches: 16,
    carcassMaterialId: 'mat_3',
    shutterMaterialId: 'mat_1',
    hardwareOptionId: 'hw_3',
  },
  {
    id: 'preset_crockery',
    category: 'Crockery Unit',
    defaultName: 'Dining Glass Display Crockery Unit',
    defaultPricingModel: 'sqft',
    defaultRate: 1550,
    defaultDepthInches: 18,
    carcassMaterialId: 'mat_3',
    shutterMaterialId: 'mat_5',
    hardwareOptionId: 'hw_1',
  },
  {
    id: 'preset_pooja',
    category: 'Pooja Unit',
    defaultName: 'Custom CNC Cut Mandir Pooja Unit',
    defaultPricingModel: 'sqft',
    defaultRate: 1950,
    defaultDepthInches: 18,
    carcassMaterialId: 'mat_2',
    shutterMaterialId: 'mat_6',
    hardwareOptionId: 'hw_4',
  },
  {
    id: 'preset_study',
    category: 'Study Unit',
    defaultName: 'Kids Bedroom Study Table & Bookcase',
    defaultPricingModel: 'sqft',
    defaultRate: 1250,
    defaultDepthInches: 20,
    carcassMaterialId: 'mat_3',
    shutterMaterialId: 'mat_1',
    hardwareOptionId: 'hw_3',
  },
  {
    id: 'preset_loft',
    category: 'Loft',
    defaultName: 'Overhead Storage Loft Unit',
    defaultPricingModel: 'sqft',
    defaultRate: 950,
    defaultDepthInches: 24,
    carcassMaterialId: 'mat_3',
    shutterMaterialId: 'mat_1',
    hardwareOptionId: 'hw_3',
  },
];

export const DEFAULT_CUSTOMERS: Customer[] = [];
